name: Lint Action
description: 'GitHub action for detecting linting errors'
inputs:
  black:
    description: Enable or disable Black checks
    required: false
    default: "false"
  black_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  black_dir:
    description: Directory where the Black command should be run
    required: false
  black_extensions:
    description: Extensions of files to check with Black
    required: false
    default: "py"

  flake8:
    description: Enable or disable Flake8 checks
    required: false
    default: "false"
  flake8_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  flake8_dir:
    description: Directory where the Flake8 command should be run
    required: false
runs:
  using: 'node16'
  main: 'index.js'