name: Lint Action
description: 'GitHub action for detecting linting errors'
inputs:
  github_token:
    description: GitHub Token
    required: false
  repo_name:
    description: Repository Name
    required: true
  owner:
    description: Owner Name
    required: true
  base_sha:
    description: Base sha of PR
    required: true
  head_sha:
    description: Head sha of Commit
    required: true
  black:
    description: Enable Black checks
    required: false
    default: "false"
  flake8:
    description: Enable Flake8 checks
    required: false
    default: "false"
runs:
  using: 'node16'
  main: 'index.js'